create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create function private.is_verified(person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select person is not null and exists(select 1 from verified_emails where profile_id=person) $$;
create function private.is_current_member(person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_verified(person) and exists(select 1 from memberships m join academic_years ay on ay.id=m.academic_year_id where m.profile_id=person and m.category='incumbent' and current_date between m.starts_on and coalesce(m.ends_on,current_date) and ay.lifecycle='active') $$;
create function private.has_active_appointment(positions appointment_position[],person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_verified(person) and exists(select 1 from appointments a join committees c on c.id=a.committee_id join academic_years ay on ay.id=c.academic_year_id where a.profile_id=person and a.position=any(positions) and a.state='active' and now() between a.starts_at and coalesce(a.ends_at,'infinity') and c.state='active' and ay.lifecycle='active') $$;
create function private.is_exco(person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.has_active_appointment(array['president','vice_president','secretary','welfare_fundraising_manager','external_events_director','internal_events_director','content_creation_publicity_director']::appointment_position[],person) $$;
create function private.can_read_calendar(person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_current_member(person) or private.has_active_appointment(array['student_advisor']::appointment_position[],person) $$;
create function private.has_capability(wanted capability_name,target_event uuid default null,target_year uuid default null,target_semester smallint default null,person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_verified(person) and exists(select 1 from capability_grants g where g.grantee_id=person and g.capability=wanted and now()>=g.starts_at and (g.expires_at is null or now()<g.expires_at) and g.revoked_at is null and ((g.scope='global') or (g.scope='semester' and g.academic_year_id=target_year and g.semester=target_semester) or (g.scope='event' and g.event_id=target_event))) $$;
create function private.can_edit_event(target events,person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_exco(person) or private.has_capability('calendar_edit',target.id,target.academic_year_id,target.semester,person) $$;
create function private.can_read_task(target planning_tasks,person uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select private.is_verified(person) and (private.is_exco(person) or (private.is_current_member(person) and (target.visibility='all_members' or exists(select 1 from task_team_assignments tta join appointments a on a.team_id=tta.team_id where tta.task_id=target.id and a.profile_id=person and a.state='active' and now() between a.starts_at and coalesce(a.ends_at,'infinity'))))) $$;

revoke all on all functions in schema private from public,anon,authenticated;
grant usage on schema public to anon,authenticated;

do $$ declare t text; begin foreach t in array array['profiles','verified_emails','academic_years','memberships','committees','teams','appointments','capability_grants','trek_entitlements','events','event_team_assignments','planning_tasks','task_team_assignments','task_assignees','event_links','attachment_metadata','public_event_publications','public_event_recaps','audit_entries','import_runs'] loop execute format('alter table public.%I enable row level security',t); execute format('alter table public.%I force row level security',t); end loop; end $$;

create policy calendar_read on events for select to authenticated using(deleted_at is null and private.can_read_calendar());
create policy calendar_insert on events for insert to authenticated with check(private.is_exco() or private.has_capability('calendar_edit',null,academic_year_id,semester));
create policy calendar_update on events for update to authenticated using(deleted_at is null and private.can_edit_event(events)) with check(private.can_edit_event(events));
create policy event_teams_read on event_team_assignments for select to authenticated using(exists(select 1 from events e where e.id=event_id and private.can_read_calendar()));
create policy event_links_read on event_links for select to authenticated using(exists(select 1 from events e where e.id=event_id and private.can_read_calendar()));
create policy tasks_read on planning_tasks for select to authenticated using(deleted_at is null and private.can_read_task(planning_tasks));
create policy tasks_write on planning_tasks for all to authenticated using(private.is_exco()) with check(private.is_exco());
create policy task_teams_read on task_team_assignments for select to authenticated using(exists(select 1 from planning_tasks t where t.id=task_id and private.can_read_task(t)));
create policy task_assignees_read on task_assignees for select to authenticated using(exists(select 1 from planning_tasks t where t.id=task_id and private.can_read_task(t)));
create policy attachments_read on attachment_metadata for select to authenticated using((event_id is not null and exists(select 1 from events e where e.id=event_id and private.can_read_calendar())) or (task_id is not null and exists(select 1 from planning_tasks t where t.id=task_id and private.can_read_task(t))));
create policy published_promotions_public on public_event_publications for select to anon,authenticated using(deleted_at is null and state='published' and (publish_from is null or now()>=publish_from) and (publish_until is null or now()<publish_until));
create policy promotion_drafts on public_event_publications for select to authenticated using(private.is_exco() or private.has_capability('public_event_prepare') or private.has_capability('public_event_publish'));
create policy promotion_prepare on public_event_publications for insert to authenticated with check(private.is_exco() or private.has_capability('public_event_prepare'));
create policy promotion_publish on public_event_publications for update to authenticated using(private.is_exco() or private.has_capability('public_event_publish')) with check(private.is_exco() or private.has_capability('public_event_publish'));
create policy published_recaps_public on public_event_recaps for select to anon,authenticated using(deleted_at is null and state='published');

create function public.update_event_checked(target_id uuid,expected_revision bigint,new_name text,new_status event_status) returns events language plpgsql security definer set search_path=public,pg_temp as $$ declare result events; current_row events; begin select * into current_row from events where id=target_id; if current_row.id is null then raise exception 'event not found' using errcode='P0002'; end if; if not private.can_edit_event(current_row) then raise exception 'forbidden' using errcode='42501'; end if; update events set name=new_name,status=new_status,revision=revision+1,updated_at=statement_timestamp(),updated_by=auth.uid() where id=target_id and revision=expected_revision and deleted_at is null returning * into result; if result.id is null then if exists(select 1 from events where id=target_id) then raise exception 'revision conflict' using errcode='40001'; else raise exception 'event not found' using errcode='P0002'; end if; end if; insert into audit_entries(actor_id,action,entity_type,entity_id,entity_revision,after_data) values(auth.uid(),'update','event',result.id,result.revision,to_jsonb(result)); return result; end $$;
create function public.soft_delete_event_checked(target_id uuid,expected_revision bigint) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare prior events; begin select * into prior from events where id=target_id and deleted_at is null for update; if prior.id is null then raise exception 'event not found' using errcode='P0002'; end if; if not private.can_edit_event(prior) then raise exception 'forbidden' using errcode='42501'; end if; if prior.revision<>expected_revision then raise exception 'revision conflict' using errcode='40001'; end if; update events set deleted_at=statement_timestamp(),deleted_by=auth.uid(),updated_at=statement_timestamp(),updated_by=auth.uid(),revision=revision+1 where id=target_id; update planning_tasks set deleted_at=statement_timestamp(),deleted_by=auth.uid(),updated_at=statement_timestamp(),updated_by=auth.uid(),revision=revision+1 where event_id=target_id and deleted_at is null; insert into audit_entries(actor_id,action,entity_type,entity_id,entity_revision,before_data) values(auth.uid(),'soft_delete','event',target_id,expected_revision,to_jsonb(prior)); end $$;
revoke all on function public.update_event_checked(uuid,bigint,text,event_status),public.soft_delete_event_checked(uuid,bigint) from public,anon;
grant execute on function public.update_event_checked(uuid,bigint,text,event_status),public.soft_delete_event_checked(uuid,bigint) to authenticated;
-- No client policies exist for audit_entries/import_runs/identity administration: default deny.
